[project]
name = 'BeehiveChain-Colony-Network'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.beehive-health-registry]
path = 'contracts/beehive-health-registry.clar'
clarity_version = 3
epoch = '3.2'

[contracts.beekeeping-conservation-rewards]
path = 'contracts/beekeeping-conservation-rewards.clar'
clarity_version = 3
epoch = 'latest'

[contracts.disease-prevention-monitoring]
path = 'contracts/disease-prevention-monitoring.clar'
clarity_version = 3
epoch = '3.2'

[contracts.pollinator-conservation-tracking]
path = 'contracts/pollinator-conservation-tracking.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
